### PR TITLE
LPS-71717 Field name generation based on the field label should be disabled if there're content associated to the structure

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi @ctampoya, could you please create a functional test for this?

I think this bug is a regression, I remember we fixed this before.

cc @vicnate5 @leoadb

### CODE REVIEW

**Comment by ctampoya** [comment]
Submitted POSHI test for review https://github.com/vicnate5/liferay-portal/pull/771

**Comment by ctampoya** [comment]
Hi @marcellustavares! I cannot add a toggle at the command level for the new testcase so we will have to wait until the new code is in master before we add the functional test. I already have the test written and it passes with your fixes. You can go ahead and merge the changes without the functional test =)

**Comment by marcellustavares** [comment]
Okay, thx @ctampoya!

**Comment by marcellustavares** [comment]
Sent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/157

**Pull request closed without merging**
