### PR TITLE
LPS-72621 Update tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @ctampoya,

there are two poshi tests failing in this pull(I made some changes that broken them).  Now the select field options, for select fields that are filled by a data provider, are loading only when the user interact with it (click to open the options list). I think we need just adding a delay to waiting the options be loaded.

Let me know if you need more information or some help

Thx

**Comment by ctampoya** [comment]
Thanks @rafaprax. Will you be updating this pull or be sending a new one?

**Comment by rafaprax** [comment]
@ctampoya Could you fix the poshi tests and sending a new one for the DDM subrepo?

Thx

**Comment by ctampoya** [comment]
@rafaprax Could you please take another look at this pull? There is an error with the Data Provider persisting in the Select field after saving the Form. I have attached the gif below. 


CC @marcellustavares

**Comment by rafaprax** [comment]
Thx @ctampoya I'm doing it.

**Pull request closed without merging**
